### ISSUE TITLE
"Exception message: cannot load such file -- test/unit" in RubyMine

### ISSUE THREAD

**Issue by jaaufauvre** [Mastercard/oauth1-signer-ruby#14]
After the project is loaded in RubyMine 2020.2.3, running the tests gives:

```
Fail to load: .../oauth1-signer-ruby/tests/test_get_authorization_string.rb:1
      Exception message: cannot load such file -- test/unit
[".../oauth1-signer-ruby/tests/test_get_authorization_string.rb:2:in `require'", ".../oauth1-signer-ruby/tests/test_get_authorization_string.rb:2:in `<top (required)>'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:49:in `require'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:49:in `block in require_all_test_scripts'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:42:in `each'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:42:in `require_all_test_scripts'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:187:in `<main>'"]

Fail to load: .../oauth1-signer-ruby/tests/test_get_base_uri_string.rb:1
      Exception message: cannot load such file -- test/unit
[".../oauth1-signer-ruby/tests/test_get_base_uri_string.rb:2:in `require'", ".../oauth1-signer-ruby/tests/test_get_base_uri_string.rb:2:in `<top (required)>'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:49:in `require'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:49:in `block in require_all_test_scripts'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:42:in `each'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:42:in `require_all_test_scripts'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:187:in `<main>'"]

Fail to load: .../oauth1-signer-ruby/tests/test_get_body_hash.rb:1
      Exception message: cannot load such file -- test/unit
[".../oauth1-signer-ruby/tests/test_get_body_hash.rb:2:in `require'", ".../oauth1-signer-ruby/tests/test_get_body_hash.rb:2:in `<top (required)>'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:49:in `require'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:49:in `block in require_all_test_scripts'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:42:in `each'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:42:in `require_all_test_scripts'", "C:/Program Files/JetBrains/RubyMine 2020.2/plugins/ruby/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:187:in `<main>'"]
```

**Comment by jaaufauvre** [comment]
Fixed by PR #15
